name = "Wintonpack"
author = "GabrielBoscoDeolindo"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd79d910c30e44da2f8356b20dcb5ee115e5d78e5fabd068441878b7f570b38"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
