name = "Wintonpack"
author = "GabrielBoscoDeolindo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67eba5d643480df151fbca444e0d816b4e692f54d4f27d141cbda012a8a0039c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
