name = "Wintonpack"
author = "GabrielBoscoDeolindo"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f9ceab6251a28e561970d40ae4d8a47a9d147ee374281ca4f79fcfa6b1ace90"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
