name = "Wintonpack"
author = "GabrielBoscoDeolindo"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c2924188b063107e13c681a345204119dacfbea88b3d113e09da663fd9d0c6"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
