name = "Wintonpack"
author = "GabrielBoscoDeolindo"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5179ff4262a0e98ab7313e15c925f8cc5e0893ada95de35eedba8956636d379"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
